import turtle as trtl

p = trtl.Turtle()
p.speed(1000)
def create_clouds(cloud_x, cloud_y):
    
  p.pencolor("grey")
  p.fillcolor("dark grey")
  p.penup()
  p.goto(cloud_x,cloud_y)
  p.pendown()
  p.begin_fill()
  p.circle(23)
  p.end_fill()
  p.goto(cloud_x, cloud_y)
  p.pensize(5)
  p.pencolor("light grey")
  p.circle(23,200)
  p.pencolor("grey")
  #Code below is for the second biggest circle in the cloud on the right
  p.circle(23,185)
  p.goto(cloud_x + 30, cloud_y + 1)
  p.begin_fill()
  p.circle(18)
  p.end_fill()
  p.goto(cloud_x + 30, cloud_y + 1)
  p.pensize(5)
  p.pencolor("light grey")
  p.circle(18,190)
  p.penup()
  #code below is the second biggest circle for the cloud on the left.
  p.goto(cloud_x - 35, cloud_y + 33)
  p.pendown()
  p.pencolor("dark grey")
  p.begin_fill()
  p.circle(18)
  p.end_fill()
  p.circle(18,270)
  p.pencolor("grey")
  p.circle(18,275)
  p.penup()
  #Code below is the circle for the cloud on the far left.
  p.goto(cloud_x - 39,cloud_y + 1)
  p.pendown()
  p.pencolor("dark grey")
  p.begin_fill()
  p.circle(12)
  p.end_fill()
  p.circle(12,100)
  p.pencolor("grey")
  p.pensize(5)
  p.circle(12,280)
  p.penup()
  #code below is for the medium sized circle for the cloud, before the farthest on the right. 
  p.goto(cloud_x + 60,cloud_y + 5)
  p.begin_fill()
  p.circle(15)
  p.end_fill()
  p.pendown()
  p.pencolor("light grey")
  p.circle(15,185)
  p.pencolor("dark grey")
  p.circle(15,60)
  p.pencolor("grey")
  p.circle(15,105)
  p.penup()
  #Code below is for the small circle in the cloud, farthest to the right. 
  p.goto(cloud_x + 78, cloud_y + 1)
  p.pendown()
  p.pencolor("dark grey")
  p.begin_fill()
  p.circle(12)
  p.end_fill()
  p.pencolor("light grey")
  p.circle(12,185)
  p.pencolor("dark grey")
  p.circle(12,60)
  p.pencolor("grey")
  p.circle(12,105)
  p.setheading(0)